language: java

jdk:
  - openjdk8
  
services:
  - mysql

before_script:
  - cd stock_manager
  - mysql -u root -e 'CREATE DATABASE stock_managerdb;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON stock_managerdb.* TO 'spq'@'localhost';"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - mvn clean compile install -e
  - mvn test

addons:
  sonarcloud:
    organization: "Ibaii99"
