language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  
  
services:
  - mysql

before_script:
  - mysql -u root -e 'drop user root@localhost;'
  - mysql -u root -e 'FLUSH PRIVILEGES;'
  - mysql -u root -e 'CREATE DATABASE stock_managerdb;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL ON stock_managerdb . * TO 'root'@'localhost';"

script: bash build.sh
