language: java
jdk:
  - openjdk8
services:
  - mysql
before_script:
  - cd stock_manager
  - mysql -u root -e 'CREATE DATABASE stock_managerdb;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON stock_managerdb.* TO 'spq'@'localhost';"
  
addons:
  sonarcloud:
    organization: "procesosoftware"
    token:
      secure: "qxWxvSAQEGZIagZ16Up9CdqWydGqD2Nl3h0e9b8udj4wr0U1tYnbIZ03P9WtmhAsWrcUzwhoBizDmnNHqC2e8BOxSmQIWP6qifhIQq8vnkfTjF4+14PZnI3ss0uFn75HORSv3H6WfspR13wjL52MBP71LX/9cZIPhPmqk+F1dTXvF+ZOrUbbNyZsPZNgX71R6drA9e1+2ncXAPOe+DaNi3kSqnn1Ufa9ReBsyGK87ogEtiZdWTbsrZD52wFN44zQlSNY3WLmdnj3MHb+QhAwHeX82iKBA80LZ0EJOAdqF/cSDoboTIQxzvnI/dTOZQm208eDF7d8XWRO4T71gq9XsIWjTsybEhpTTQg2wCowjAPot+C1DfnKk2l/ehcMjxNtsO11ziR6opa9dbLLIfaG9YczWcW5Y4khsfM+tMu/GSPG6j9IkoLERdKJyhYZOTm3xQl2RpLsi2oM321FX2bTcrfrKxw/A519u+eKmFwXvMkAKvWExGEHwbhFpeNI7728QbbLKlVR0A3l7V/W9/CxrqXChK4B/gu8uvEXr4Jg1xxQ1MrUol8gCDM62eWepYlXlonQA5OCurFweTnEaDxYEWq7mKMYS134DnwNYLToal9VXwGqV70yeviYJ8f7cuLOJsmohle9fc3ypuZF3YFmo0kjD+uB8QEtH3R1Ls8Z0lE=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ProcesoSoftware_stock_manager

after_success:
  - mvn clean jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
