CREATE TABLE `articulo` (
  `ID` bigint(20) NOT NULL,
  `CADUCIDAD` timestamp NULL DEFAULT NULL,
  `CATEGORIA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `DESCRIPCION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `IMAGE` mediumblob,
  `IMAGEURL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `NOMBRE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `OFERTA` float NOT NULL,
  `PRECIO` float NOT NULL,
  `STOCK` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `articulo_cestas` (
  `ID_OID` bigint(20) NOT NULL,
  `ID_EID` bigint(20) DEFAULT NULL,
  `IDX` int(11) NOT NULL,
  PRIMARY KEY (`ID_OID`,`IDX`),
  KEY `ARTICULO_CESTAS_N49` (`ID_OID`),
  KEY `ARTICULO_CESTAS_N50` (`ID_EID`),
  CONSTRAINT `ARTICULO_CESTAS_FK1` FOREIGN KEY (`ID_OID`) REFERENCES `articulo` (`ID`),
  CONSTRAINT `ARTICULO_CESTAS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `cesta` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cesta` (
  `ID` bigint(20) NOT NULL,
  `CANTIDADES` mediumblob,
  `CLIENTE_ID_OID` bigint(20) DEFAULT NULL,
  `ESTADO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `PEDIDOS_INTEGER_IDX` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CESTA_N49` (`CLIENTE_ID_OID`),
  CONSTRAINT `CESTA_FK1` FOREIGN KEY (`CLIENTE_ID_OID`) REFERENCES `cliente` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cesta_articulos` (
  `ID_OID` bigint(20) NOT NULL,
  `ID_EID` bigint(20) DEFAULT NULL,
  `IDX` int(11) NOT NULL,
  PRIMARY KEY (`ID_OID`,`IDX`),
  KEY `CESTA_ARTICULOS_N49` (`ID_OID`),
  KEY `CESTA_ARTICULOS_N50` (`ID_EID`),
  CONSTRAINT `CESTA_ARTICULOS_FK1` FOREIGN KEY (`ID_OID`) REFERENCES `cesta` (`ID`),
  CONSTRAINT `CESTA_ARTICULOS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `articulo` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cliente` (
  `ID` bigint(20) NOT NULL,
  `CARRITO_ID_OID` bigint(20) DEFAULT NULL,
  `CONTRASENYACLIENTE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `DIRECCIONCLIENTE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `EMAILCLIENTE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `FAVORITOS_ID_OID` bigint(20) DEFAULT NULL,
  `NOMBRECLIENTE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CLIENTE_U1` (`EMAILCLIENTE`),
  KEY `CLIENTE_N50` (`CARRITO_ID_OID`),
  KEY `CLIENTE_N49` (`FAVORITOS_ID_OID`),
  CONSTRAINT `CLIENTE_FK1` FOREIGN KEY (`CARRITO_ID_OID`) REFERENCES `cesta` (`ID`),
  CONSTRAINT `CLIENTE_FK2` FOREIGN KEY (`FAVORITOS_ID_OID`) REFERENCES `cesta` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `opinion` (
  `ID` bigint(20) NOT NULL,
  `CLIENTE_ID_OID` bigint(20) DEFAULT NULL,
  `TEXTO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `VALORACION` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `OPINION_N49` (`CLIENTE_ID_OID`),
  CONSTRAINT `OPINION_FK1` FOREIGN KEY (`CLIENTE_ID_OID`) REFERENCES `cliente` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sequence_table` (
  `SEQUENCE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `NEXT_VAL` bigint(20) NOT NULL,
  PRIMARY KEY (`SEQUENCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `usuario` (
  `ID` bigint(20) NOT NULL,
  `CONTRASENYA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `NOMBRE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USUARIO_U1` (`NOMBRE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vendedor` (
  `ID` bigint(20) NOT NULL,
  `EMAILVENDEDOR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `NOMBREVENDEDOR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `VENDEDOR_U1` (`EMAILVENDEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vendedor_articulos` (
  `ID_OID` bigint(20) NOT NULL,
  `ID_EID` bigint(20) DEFAULT NULL,
  `IDX` int(11) NOT NULL,
  PRIMARY KEY (`ID_OID`,`IDX`),
  KEY `VENDEDOR_ARTICULOS_N50` (`ID_EID`),
  KEY `VENDEDOR_ARTICULOS_N49` (`ID_OID`),
  CONSTRAINT `VENDEDOR_ARTICULOS_FK1` FOREIGN KEY (`ID_OID`) REFERENCES `vendedor` (`ID`),
  CONSTRAINT `VENDEDOR_ARTICULOS_FK2` FOREIGN KEY (`ID_EID`) REFERENCES `articulo` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
